### ISSUE TITLE
Bad textures on Intel GPU

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.grangerhub.Tremulous#4]
![Bad textures](https://user-images.githubusercontent.com/2339930/51803044-a6a3ee00-2250-11e9-8881-9326f8816556.png)

On ThinkPad T470s with Fedora 29. Probably a Mesa issue.

**Comment by dGr8LookinSparky** [comment]
That is actually an issue with how the range markers are done in the game logic that is included in the 1.3 client release.  As far as I know that happens for everyone.  I haven't bothered fixing it since when the new 1.3 server game logic is ready, we will be making that new game logic compatible with the latest 1.3 client (they have been developed on separate for repos for awhile, not an ideal approach, but that is where we are at the moment), but if someone else fixes it, we do except pull requests.  In the meantime, you can disable the range markers with `/cg_rangeMarkerDrawSurface 0`.
